package com.example.domain

object LanguageManager {
  enum class Language(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    TAMIL("ta", "தமிழ்"),
    TANGLISH("tanglish", "Tanglish")
  }

  fun getString(key: String, lang: String = "en"): String {
    return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
  }

  private val translations = mapOf(
    "en" to mapOf(
      "app_tagline" to "Weather that fits your life.",
      "continue_google" to "Continue with Google",
      "continue_guest" to "Continue as Guest",
      "try_demo" to "Try Demo Mode",
      "hi_user" to "Hi, %s 👋",
      "exact_locality" to "Exact Locality",
      "use_current_location" to "Use Current Location",
      "search_location" to "Search Location",
      "select_field_location" to "Select Field Location",
      "mausam_insight" to "MAUSAM Insight",
      "important_alerts" to "Important Alerts",
      "smart_suggestions" to "Smart Suggestions",
      "live_weather_plot" to "Live Weather Plot",
      "rain_probability" to "Rain Probability",
      "7day_forecast" to "7-Day Forecast",
      "quick_actions" to "Quick Actions",
      "check_crop_risk" to "Crop Risk",
      "plan_travel" to "Plan Travel",
      "find_beach" to "Find Beach",
      "change_location" to "Change Location",
      "humidity" to "Humidity",
      "wind" to "Wind",
      "feels_like" to "Feels Like",
      "uv_index" to "UV Index",
      "pressure" to "Pressure",
      "sunrise" to "Sunrise",
      "sunset" to "Sunset",
      "fitness_comfort" to "Fitness Comfort Score",
      "best_run" to "Best Running Time",
      "best_walk" to "Best Walking Time",
      "outdoor_comfort" to "Outdoor Comfort",
      "aqi" to "Air Quality Index",
      "crop_risk_title" to "Agriculture & Crop Risk",
      "capture_photo" to "Capture Field Photo",
      "upload_photo" to "Upload Field Photo",
      "my_fields" to "My Fields",
      "travel_planner" to "Travel Planner",
      "shortest_route" to "Shortest Route",
      "longer_route" to "Longer Alternative Route",
      "nearest_beach" to "Nearest Beach",
      "beach_condition" to "Beach Condition Summary",
      "ask_mausam" to "Ask MAUSAM",
      "ask_placeholder" to "Ask about rain, running, crops, travel...",
      "demo_mode_badge" to "DEMO MODE",
      "offline_mode" to "OFFLINE MODE"
    ),
    "ta" to mapOf(
      "app_tagline" to "உங்கள் வாழ்க்கைக்கு ஏற்ற வானிலை.",
      "continue_google" to "Google மூலம் தொடரவும்",
      "continue_guest" to "விருந்தினராக தொடரவும்",
      "try_demo" to "டெமோ முறை பார்க்க",
      "hi_user" to "வணக்கம், %s 👋",
      "exact_locality" to "துல்லியமான இடம்",
      "use_current_location" to "தற்போதைய இடத்தைப் பயன்படுத்து",
      "search_location" to "இடத்தை தேடுங்கள்",
      "select_field_location" to "விவசாய நில இருப்பிடம்",
      "mausam_insight" to "வானிலை பார்வை",
      "important_alerts" to "முக்கிய எச்சரிக்கைகள்",
      "smart_suggestions" to "புத்திசாலி ஆலோசனைகள்",
      "live_weather_plot" to "வானிலை வரைபடம்",
      "rain_probability" to "மழை பெய்யும் வாய்ப்பு",
      "7day_forecast" to "7 நாள் முன்னறிவிப்பு",
      "quick_actions" to "விரைவு சேவைகள்",
      "check_crop_risk" to "பயிர் பாதுகாப்பு",
      "plan_travel" to "பயண திட்டம்",
      "find_beach" to "கடற்கரை தேடு",
      "change_location" to "இடத்தை மாற்றுக",
      "humidity" to "ஈரப்பதம்",
      "wind" to "காற்று வேகம்",
      "feels_like" to "உணரப்படும் வெப்பநிலை",
      "uv_index" to "UV குறியீடு",
      "pressure" to "காற்றழுத்தம்",
      "sunrise" to "சூரிய உதயம்",
      "sunset" to "சூரிய அஸ்தமனம்",
      "fitness_comfort" to "உடற்பயிற்சி வசதி குறியீடு",
      "best_run" to "ஓடுவதற்கு சிறந்த நேரம்",
      "best_walk" to "நடைப்பயிற்சி சிறந்த நேரம்",
      "outdoor_comfort" to "வெளிப்புற சுகாதாரம்",
      "aqi" to "காற்று தரம் (AQI)",
      "crop_risk_title" to "வேளாண்மை மற்றும் பயிர் அபாய ஆய்வு",
      "capture_photo" to "நில புகைப்படம் எடு",
      "upload_photo" to "புகைப்படம் பதிவேற்று",
      "my_fields" to "எனது வயல்கள்",
      "travel_planner" to "பயண வழிகாட்டி",
      "shortest_route" to "குறுகிய வழி",
      "longer_route" to "மாற்று நெடுஞ்சாலை வழி",
      "nearest_beach" to "அருகிலுள்ள கடற்கரை",
      "beach_condition" to "கடற்கரை பாதுகாப்பு நிலை",
      "ask_mausam" to "மௌசம் கேளுங்கள்",
      "ask_placeholder" to "மழை, பயணம், பயிர் குறித்து கேளுங்கள்...",
      "demo_mode_badge" to "டெமோ முறை",
      "offline_mode" to "ஆஃப்லைன் முறை"
    ),
    "tanglish" to mapOf(
      "app_tagline" to "Weather that fits your life.",
      "continue_google" to "Google oda continue pannunga",
      "continue_guest" to "Guest-ah continue pannunga",
      "try_demo" to "Demo Mode parkalam",
      "hi_user" to "Vanakkam, %s 👋",
      "exact_locality" to "Exact Location",
      "use_current_location" to "Current Location use pannu",
      "search_location" to "Location Thedu",
      "select_field_location" to "Vayalkaadu Location",
      "mausam_insight" to "MAUSAM Insight",
      "important_alerts" to "Important Alerts",
      "smart_suggestions" to "Smart Suggestions",
      "live_weather_plot" to "Weather Chart",
      "rain_probability" to "Mazhai Vara Chance",
      "7day_forecast" to "7-Day Forecast",
      "quick_actions" to "Quick Actions",
      "check_crop_risk" to "Payir Risk Check",
      "plan_travel" to "Travel Plan",
      "find_beach" to "Beach Find Pannu",
      "change_location" to "Location Mathu",
      "humidity" to "Humidity",
      "wind" to "Kaathu Vegam",
      "feels_like" to "Feels Like",
      "uv_index" to "UV Index",
      "pressure" to "Pressure",
      "sunrise" to "Surya Udhayam",
      "sunset" to "Surya Asthamanam",
      "fitness_comfort" to "Workout Comfort Score",
      "best_run" to "Running-ku Nalla Time",
      "best_walk" to "Walking-ku Nalla Time",
      "outdoor_comfort" to "Outdoor Comfort",
      "aqi" to "Kaathu Tharam (AQI)",
      "crop_risk_title" to "Agriculture & Crop Risk",
      "capture_photo" to "Vayal Photo Edunga",
      "upload_photo" to "Photo Upload Pannunga",
      "my_fields" to "En Vayalkaadu",
      "travel_planner" to "Travel Route Guide",
      "shortest_route" to "Shortest Route",
      "longer_route" to "Bypass Highway Route",
      "nearest_beach" to "Pakkatula Beach",
      "beach_condition" to "Beach Safety Status",
      "ask_mausam" to "Ask MAUSAM",
      "ask_placeholder" to "Mazhai varuma, running pogalama...",
      "demo_mode_badge" to "DEMO MODE",
      "offline_mode" to "OFFLINE MODE"
    )
  )
}
